---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: hotel
  name: hotel-deployment
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      run: hotel
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: hotel
    spec:
      containers:
        - image: hotel:v1
          imagePullPolicy: IfNotPresent
          name: hotel
          ports:
            - name: port4567
              containerPort: 4567
              protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
