---
apiVersion: v1
kind: Service
metadata:
  labels:
    myredis: redis
  name: redis
  namespace: default
spec:
  ports:
    - port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    myredis: redis
  sessionAffinity: None
  type: ClusterIP
